apiVersion: v1
kind: Service
metadata:
  name: allure-service
spec:
  selector:
    app: allure-server
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
