apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
spec:
  selector:
    app: selenium-hub
  ports:
  - protocol: TCP
    port: {{ .Values.hub.port }}
    targetPort: {{ .Values.hub.port }}
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-node-chrome
spec:
  selector:
    app: selenium-node-chrome
  ports:
  - protocol: TCP
    port: {{ .Values.chromeNode.vncPort }}
    targetPort: {{ .Values.chromeNode.vncPort }}
  - protocol: TCP
    port: {{ .Values.chromeNode.nodePort }}
    targetPort: {{ .Values.chromeNode.nodePort }}
  type: LoadBalancer
