apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
spec:
  selector:
    app: selenium-hub
  ports:
  - name: web-ui  # 👈 Added port name
    protocol: TCP
    port: {{ .Values.hub.port }}
    targetPort: {{ .Values.hub.port }}
    {{- if eq .Values.hub.kind "kind" }}
    nodePort: {{ .Values.hub.nodePort }}
    {{- end }}
  type: {{ if eq .Values.hub.kind "cloud" }}LoadBalancer{{ else }}NodePort{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-node-chrome
spec:
  selector:
    app: selenium-node-chrome
  ports:
  - name: vnc-ui  # 👈 Added port name
    protocol: TCP
    port: {{ .Values.chromeNode.vncPort }}
    targetPort: {{ .Values.chromeNode.vncPort }}
    {{- if eq .Values.hub.kind "kind" }}
    nodePort: {{ .Values.chromeNode.vncNodePort }}
    {{- end }}
  - name: grid-node  # 👈 Added port name
    protocol: TCP
    port: {{ .Values.chromeNode.nodePort }}
    targetPort: {{ .Values.chromeNode.nodePort }}
  type: {{ if eq .Values.hub.kind "cloud" }}LoadBalancer{{ else }}NodePort{{ end }}
