apiVersion: apps/v1
kind: Deployment
metadata:
  name: allure-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allure-server
  template:
    metadata:
      labels:
        app: allure-server
    spec:
      containers:
      - name: allure
        image: frankescobar/allure-docker-service
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: allure-service
spec:
  selector:
    app: allure-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5050
  type: LoadBalancer
