apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub
        ports:
        - containerPort: 4444
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-node-chrome
  template:
    metadata:
      labels:
        app: selenium-node-chrome
    spec:
      containers:
      - name: selenium-node-chrome
        image: selenium/node-chrome-debug
        env:
        - name: HUB_HOST
          value: "selenium-hub"
        ports:
        - containerPort: 5900
        - containerPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
spec:
  selector:
    app: selenium-hub
  ports:
  - protocol: TCP
    port: 4444
    targetPort: 4444
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-node-chrome
spec:
  selector:
    app: selenium-node-chrome
  ports:
  - protocol: TCP
    port: 5900
    targetPort: 5900
  type: LoadBalancer
