apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-poc
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/your-git-repo/k8s-poc.git
    targetRevision: main
    path: manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
